'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ArenaFightersII.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ABOUT_M7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ABOUT_M7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adimantiteBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adimantiteBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property af2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("af2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property agilityRing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agilityRing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aluminumBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aluminumBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ARENA_FIGHTERS_TITLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARENA_FIGHTERS_TITLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asentine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asentine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property att100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("att100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property att25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("att25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property att50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("att50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BACKGROUND_GAME() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BACKGROUND_GAME", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BACKGROUND_MENU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BACKGROUND_MENU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bartAmulet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bartAmulet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property basicStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basicStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beast100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beast100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beast25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beast25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beast50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beast50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerAlphaBurnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerAlphaBurnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerAlphaCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerAlphaCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerAlphaUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerAlphaUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerBurnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerBurnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btRavagerUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btRavagerUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_ABOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_ABOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_CHAR_SCRN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_CHAR_SCRN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_DONATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_DONATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_INV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_INV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_LOAD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_LOAD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_MENU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_MENU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_NEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_NEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_QUIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_QUIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BUTTON_SKILLS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTON_SKILLS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cb_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cb_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cb_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cb_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cb_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cb_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cbAmulet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cbAmulet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clothBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clothBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clothBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clothBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clothHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clothHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clothLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clothLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copperBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copperBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property corruptScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corruptScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cpPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Crosgate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crosgate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dandifer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dandifer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Deadwoe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Deadwoe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property def100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("def100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property def25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("def25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property def50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("def50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property defAmulet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defAmulet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property df100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("df100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property df25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("df25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property df50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("df50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property draBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property draBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dragonScaleBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragonScaleBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property draHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property draLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Faeshuun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Faeshuun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fdraBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fdraBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fdraBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fdraBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fdraHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fdraHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fdraLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fdraLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fishBurnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fishBurnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fStaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fStaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gDagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gDagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grCape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grCape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property healthRing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("healthRing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hp100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hp25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hp50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hpRecov100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hpRecov100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hpRecov25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hpRecov25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hpRecov50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hpRecov50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ironBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ironBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jokerHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jokerHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leaBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leaBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leaHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property leaLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legCape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legCape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legDagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legDagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legRing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legRing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legStaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legStaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Litenadine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Litenadine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lStaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lStaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mag100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mag100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mag25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mag25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mag50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mag50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magicAmulet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magicAmulet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maiBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maiBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maiBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maiBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maiHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maiHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maiLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maiLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mantaReyBurnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mantaReyBurnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mantaReyCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mantaReyCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mantaReyUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mantaReyUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nothng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nothng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NPC_Bandit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC_Bandit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oDagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oDagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plaBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plaBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plaBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plaBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plaHelm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plaHelm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plaLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plaLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preset_Extremist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preset_Extremist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preset_Mage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preset_Mage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preset_Rogue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preset_Rogue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preset_Skiller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preset_Skiller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property preset_Warrior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preset_Warrior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pStaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pStaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ranite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ranite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rDagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rDagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redCape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redCape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ryeleaf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ryeleaf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salmonCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salmonCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salmonUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salmonUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skillRing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skillRing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spec100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spec100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spec25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spec25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spec50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spec50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SPLASH_SCREEN_BACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SPLASH_SCREEN_BACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property springFishBurnt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("springFishBurnt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property springFishCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("springFishCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property springFishUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("springFishUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property steelBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steelBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property str100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("str100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property str25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("str25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property str50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("str50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property strAmulet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strAmulet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tank100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tank100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tank25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tank25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tank50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tank50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tealCape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tealCape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toughskin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toughskin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property troutCooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("troutCooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property troutUncooked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("troutUncooked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wStaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wStaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
